apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: red-namespace
spec:
  selector:
    app.kubernetes.io/name: redvm
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
